name: stackfood_multivendor_restaurant
description: An application for multivendor ecommerce restaurant.
publish_to: 'none'
version: 1.0.2+10

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  path_provider: ^2.1.4
  url_strategy: ^0.3.0
  shimmer_animation: 2.2.1
  image_picker: ^1.1.2
  http: ^1.2.2
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.1
  vibration: ^2.0.0
  audioplayers: ^6.0.0
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.0.0
  phone_numbers_parser: ^8.3.0
  country_code_picker: ^3.0.0
  flutter_widget_from_html_core: ^0.15.2
  google_maps_flutter: ^2.9.0
  geolocator: ^9.0.2
  card_swiper: ^3.0.1
  print_bluetooth_thermal: ^1.1.4
  flutter_esc_pos_utils: ^1.0.1
  screenshot: ^3.0.0
  image: ^4.2.0
  modal_bottom_sheet: ^3.0.0
  intl: ^0.19.0
  path: ^1.9.0
  http_parser: ^4.1.0
  dotted_border: ^2.1.0
  carousel_slider: ^5.0.0
  photo_view: ^0.15.0
  flutter_inappwebview: ^6.1.5
  just_the_tooltip: ^0.0.12
  file_picker: ^8.1.2
  custom_info_window: ^1.0.1
  syncfusion_flutter_charts: ^27.1.53
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10+1
  flutter_slidable: ^3.1.2
  video_player: ^2.9.1
  chewie: ^1.8.3
  pdf: ^3.11.1
  file_saver: ^0.3.1
  in_app_update: ^4.2.3

dependency_overrides:
  collection: ^1.19.0
  web: ^1.0.0
  geolocator_android: 4.6.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900